# Generated by Django 5.1 on 2026-03-31 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('sepay', 'SePay (Chuyển khoản)'), ('cod', 'Thanh toán khi nhận hàng')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('failed', 'Thất bại'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='SePayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepay_id', models.BigIntegerField(unique=True)),
                ('gateway', models.CharField(max_length=100)),
                ('transaction_date', models.DateTimeField()),
                ('account_number', models.CharField(max_length=100)),
                ('sub_account', models.CharField(blank=True, max_length=250, null=True)),
                ('transfer_type', models.CharField(max_length=10)),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('accumulated', models.DecimalField(decimal_places=2, max_digits=14)),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('content', models.TextField(blank=True)),
                ('reference_code', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sepay_transactions', to='payments.payment')),
            ],
        ),
    ]
